// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.Eventos.Shared;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Module.Eventos.Migrations
{
    [DbContext(typeof(EventosDbContext))]
    [Migration("20260919023528_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Eventos")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Module.Eventos.Domain.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("EventoCancelamentoMotivo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EventoCapacidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EventoDataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EventoDataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventoDescricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventoFormato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EventoLinkRemoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventoSituacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("LocalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventoDataInicio");

                    b.HasIndex("EventoSituacao");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("LocalId");

                    b.ToTable("Eventos", "Eventos");
                });

            modelBuilder.Entity("Module.Eventos.Domain.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("InscricaoCanceladaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InscricaoRealizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InscricaoSituacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("EventoId", "InscricaoSituacao");

                    b.HasIndex("EventoId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inscricoes_EventoId_PessoaId_Confirmada")
                        .HasFilter("\"InscricaoSituacao\" = 'Confirmada'");

                    b.ToTable("Inscricoes", "Eventos");
                });

            modelBuilder.Entity("Shared.Data.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn", "LockedUntil", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_Pendentes");

                    b.ToTable("OutboxMessages", "Eventos");
                });

            modelBuilder.Entity("Module.Eventos.Domain.Inscricao", b =>
                {
                    b.HasOne("Module.Eventos.Domain.Evento", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Module.Eventos.Domain.Evento", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
