<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tests.Architecture</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/modules/Module.Auditoria/Module.Auditoria.csproj" />
    <ProjectReference Include="../../src/modules/Module.Eventos/Module.Eventos.csproj" />
    <ProjectReference Include="../../src/modules/Module.Identidade/Module.Identidade.csproj" />
    <ProjectReference Include="../../src/modules/Module.Locais/Module.Locais.csproj" />
    <ProjectReference Include="../../src/modules/Module.Palestras/Module.Palestras.csproj" />
    <ProjectReference Include="../../src/modules/Module.Pessoas/Module.Pessoas.csproj" />
    <ProjectReference Include="../../src/shared/Shared.Http/Shared.Http.csproj" />
    <ProjectReference Include="../../src/shared/Shared.WebHost/Shared.WebHost.csproj" />
  </ItemGroup>
</Project>
