// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.Palestras.Shared;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Module.Palestras.Migrations
{
    [DbContext(typeof(PalestrasDbContext))]
    [Migration("20260919023753_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Palestras")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Module.Palestras.Domain.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CertificadoCargaHorariaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("CertificadoCodigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character(12)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CertificadoEmitidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PalestraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificadoCodigo")
                        .IsUnique();

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("PalestraId", "PessoaId");

                    b.ToTable("Certificados", "Palestras");
                });

            modelBuilder.Entity("Module.Palestras.Domain.Palestra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PalestraDescricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("PalestraFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PalestraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PalestraTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SalaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("SalaId", "PalestraInicio");

                    b.ToTable("Palestras", "Palestras");
                });

            modelBuilder.Entity("Module.Palestras.Domain.PalestraConteudo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ConteudoDescricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ConteudoTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConteudoTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConteudoUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PalestraId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("PalestraId");

                    b.ToTable("PalestraConteudos", "Palestras");
                });

            modelBuilder.Entity("Module.Palestras.Domain.PalestraPalestrante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PalestraId")
                        .HasColumnType("uuid");

                    b.Property<string>("PalestrantePapel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PalestraId", "PessoaId")
                        .IsUnique()
                        .HasFilter("\"ExcluidoEm\" IS NULL");

                    b.ToTable("PalestraPalestrantes", "Palestras");
                });

            modelBuilder.Entity("Module.Palestras.Domain.Presenca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstaAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExcluidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PalestraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PresencaRegistradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("PessoaId");

                    b.HasIndex("PalestraId", "PessoaId")
                        .IsUnique()
                        .HasFilter("\"ExcluidoEm\" IS NULL");

                    b.ToTable("Presencas", "Palestras");
                });

            modelBuilder.Entity("Shared.Data.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn", "LockedUntil", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_Pendentes");

                    b.ToTable("OutboxMessages", "Palestras");
                });

            modelBuilder.Entity("Module.Palestras.Domain.Certificado", b =>
                {
                    b.HasOne("Module.Palestras.Domain.Palestra", null)
                        .WithMany("Certificados")
                        .HasForeignKey("PalestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Palestras.Domain.PalestraConteudo", b =>
                {
                    b.HasOne("Module.Palestras.Domain.Palestra", null)
                        .WithMany("Conteudos")
                        .HasForeignKey("PalestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Palestras.Domain.PalestraPalestrante", b =>
                {
                    b.HasOne("Module.Palestras.Domain.Palestra", null)
                        .WithMany("Palestrantes")
                        .HasForeignKey("PalestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Palestras.Domain.Presenca", b =>
                {
                    b.HasOne("Module.Palestras.Domain.Palestra", null)
                        .WithMany("Presencas")
                        .HasForeignKey("PalestraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Module.Palestras.Domain.Palestra", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Conteudos");

                    b.Navigation("Palestrantes");

                    b.Navigation("Presencas");
                });
#pragma warning restore 612, 618
        }
    }
}
